name: round
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  sqflite: any

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  # - images/a_dot_ham.jpeg
  assets:
    - images/pyramid.jpg
    - images/mosque.jpg
    - images/musem.jpg
    - images/museum.jpg
    - images/park.jpg
    - images/map.jpg
    - images/backk.jpg
    - images/ff.jpg

  #museum
    - images/meusum/eltafl.jpg
    - images/meusum/elfonon .jpg
    - images/meusum/4am3.jpg
    - images/meusum/ma7modKhlial.jpg
    - images/meusum/elMasry.jpg
    - images/meusum/elfanElslamy.jpg
    - images/meusum/elgeology.jpg
    - images/meusum/elkhazafElEslamy.jpg
    - images/meusum/el7adeth.jpg
    - images/meusum/elkomy.jpg
    - images/meusum/Elkomy ll 7adara.jpg
    - images/meusum/el7ayoan.jpg
    - images/meusum/alkabty .jpg
    - images/meusum/kaserAbdeen.jpg
    - images/meusum/elnasygElmasry.jpg
    - images/meusum/elzeraye.jpg
    - images/meusum/mo7amedAli.jpg
    - images/meusum/anderson.jpg
    - images/meusum/elgamya.jpg
    - images/meusum/el7arf.jpg
    - images/meusum/elshorta.jpg
    - images/meusum/mostafaKamel .jpg
    - images/meusum/omKolsom.jpg

  #mosque

    - images/mosques/amr.jpg
    - images/mosques/al7akm.jpg
    - images/mosques/al70san.jpg
    - images/mosques/alakmar.jpg
    - images/mosques/alazhr.jpg
    - images/mosques/asha.jpg
    - images/mosques/barkok.jpg
    - images/mosques/ebntolon.jpg
    - images/mosques/El7amdyaElshalya.jpg
    - images/mosques/elma7modia.jpg
    - images/mosques/elrfaay.jpg
    - images/mosques/elsoltanAboAlala.jpg
    - images/mosques/kaherElttar.jpg
    - images/mosques/kanybay.jpg
    - images/mosques/mo7medali.jpg
    - images/mosques/moaidshekh.jpg
    - images/mosques/nafisa.jpg
    - images/mosques/salahElden.jpg
    - images/mosques/zyned.jpg
    - images/mosques/aboEldahb.jpg

  #pyramids

    - images/peyrmides/aisha.jpg
    - images/peyrmides/babElfoto7.jpg
    - images/peyrmides/babElnasr.jpg
    - images/peyrmides/babzewala.jpg
    - images/peyrmides/baron.jpg
    - images/peyrmides/basher.jpg
    - images/peyrmides/bashtak.jpg
    - images/peyrmides/Ben_Ezra.jpg
    - images/peyrmides/elborg.jpg
    - images/peyrmides/7rm.jpg
    - images/peyrmides/mo3lqa.jpg
    - images/peyrmides/elforonia.jpg
    - images/peyrmides/elmo2az.jpg
    - images/peyrmides/elobra.jpg
    - images/peyrmides/elroda.jpg
    - images/peyrmides/gaohara.jpg
    - images/peyrmides/kalaoon.jpg
    - images/peyrmides/khanelkalil.jpg
    - images/peyrmides/taz.jpg

  #park

    - images/park/7oria.jpg
    - images/park/7ywan.jpg
    - images/park/alasher.jpg
    - images/park/alyabanya.jpg
    - images/park/asmak.jpg
    - images/park/andalos.jpg
    - images/park/azher.jpg
    - images/park/dolia.jpg
    - images/park/ebnsandar.jpg
    - images/park/elmanyl.jpg
    - images/park/eloroba.jpg
    - images/park/elroda.jpg
    - images/park/fostat.jpg
    - images/park/frdos.jpg
    - images/park/lotes.jpg
    - images/park/merland.jpg
    - images/park/omklsom.jpg
    - images/park/senia.jpg
    - images/park/sfari.jpg
    - images/park/zaid.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
  - family: Harmattan
    fonts:
    - asset: fonts/Harmattan-Regular.ttf

  - family: Rakkas
    fonts:
    - asset: fonts/Rakkas-Regular.ttf

  - family: Lemonada
    fonts:
    - asset: fonts/Lemonada-VariableFont_wght.ttf
